
@host=http://localhost:9100/api

###

POST {{host}}/login
Content-Type: application/json


###

GET {{host}}/todo

###

GET {{host}}/todo/1

###

POST {{host}}/todo
Content-Type:  application/json

{
   "task" : "{{$random.alphabetic(10)}}"
}

###

PUT {{host}}/todo/1
Content-Type: application/json

{
  "task" : "{{$random.alphabetic(10)}}"
}

###

DELETE {{host}}/todo/1

###

POST {{host}}/person
Content-Type: application/json

{
  "name" : "cash"
}

###

GET {{host}}/person/1/todo


###

POST {{host}}/upload
Content-Type: multipart/form-data; charset=utf-8; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.json"
Content-Type: application/json

< ./test.json
--WebAppBoundary

###
POST {{host}}/upload
Content-Type: application/x-www-form-urlencoded

id = 999
