
@host=http://localhost:9100/api

###

POST {{host}}/login
Content-Type: application/json


###

GET {{host}}/todo

###

GET {{host}}/todo/1

###

POST {{host}}/todo
Content-Type:  application/json

{
   "task" : "{{$random.alphabetic(10)}}"
}

###

PUT {{host}}/todo/1
Content-Type: application/json

{
  "task" : "{{$random.alphabetic(10)}}"
}

###

DELETE {{host}}/todo/1

###

POST {{host}}/person
Content-Type: application/json

{
  "name" : "cash"
}

###

GET {{host}}/person/1/todo